apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts-db
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts-db.keptne2e-dev.34.66.10.32.xip.io
  - carts-db
  http:
  - route:
    - destination:
        host: carts-db.keptne2e-dev.svc.cluster.local
